version: '3.1'

services:
  mcserver:
    image: ghcr.io/shie1/logiscool-minecraft:master
    container_name: logiscool-minecraft
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 25565:25565
    environment:
      MAXPLAYERS: $MAXPLAYERS
      ONLINEMODE: $ONLINEMODE
      RAM: $RAM
    volumes:
      - mcserver:/mcserver

volumes:
  mcserver:
    external:
      name: mcserver