version: '3.1'

services:
  mcserver:
    image: ghcr.io/shie1/logiscool-minecraft:master
    container_name: logiscool-minecraft
    restart: always
    ports:
      - 25565:25565
    environment:
      MAXPLAYERS: $MAXPLAYERS
      ONLINEMODE: $ONLINEMODE
      RAM: $RAM
    volumes:
      - /home/test/minecraftserver:/server